#!/bin/bash

# Absolute path to the scripts directory
SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

DB_NAME="dataservice"
DB_PASS=$(cat db_pass.txt)

OUT_FILE_NAME="labbackup"
VERSION="v0.2.0"
OUT_FILE="$OUT_FILE_NAME-$VERSION.tar"

# stop the services before taking the dump
$SCRIPTS_DIR./stop

# take the dump
mysqldump -u root -p$DB_PASS $DB_NAME > $DB_NAME.sql
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while taking db dump."
  echo "Aborting backup."
  exit 1;
fi

# start back the services
$SCRIPTS_DIR./start

# tar the $DB_NAME.sql file
tar cfvz $OUT_FILE $DB_NAME.sql
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while tar-ing the dump."
  echo "Aborting backup."
  exit 1;
fi

echo "Backup successful."
exit 0;

